### ISSUE TITLE
Content script is emitted as an empty chunk

### ISSUE THREAD

**Issue by anarchylimes** [extend-chrome/rollup-plugin-chrome-extension#55] opened 2020-10-06 15:43 UTC
### Google search terms

rollup content script web extension

### Describe the bug

When using a content script to inject code into the webpage from the extension, the content script, defined in the rollup.config.js as 

```  {
    input: "src/libs/content.js",
    output: {
      sourcemap: true,
      format: "iife",
      name: "content",
      file: "public/build/content.bundle.js",
    }
```

is generated in the public/build folder correctly. However when it's finally copied to the list folder, this message comes up 

```
(!) Generated an empty chunk
build/content.bundle
```

and the content.bundle.js, which has the appropriate code inside of it in the build folder, now is blank in the dist folder.

### How do we reproduce?

specify a content script area  in the manifest 

```
  "content_scripts": [
    {
      "matches": [
        "http://*/*",
        "https://*/*"
      ],
      "js": ["build/content.bundle.js"]
    }
  ]
```

write code into the content script located at src/libs (or whatever folder you use to house your JS)/content.js

### Expected behavior

The content script should be bundled, and copied to the dist folder ready for the extension to inject into the webpage

### Actual behavior

The content.bundle.js emitted in the dist folder is blank.

### Please complete the following information:

- Operating System: MacOS
- Browser: Chrome
- Node Version: 14.12.0

**Comment by jacksteamdev** [comment] 2020-10-06 22:05
@anarchylimes The plugin parses `manifest.json` to find your content script, so your config would look like this:

```javascript
```

**Comment by jacksteamdev** [comment] 2020-10-06 22:08
Whoops! My old GitHub enemy, `Ctrl+Enter`, closed another issue on me. 😒

Answer is forthcoming...

**Comment by jacksteamdev** [comment] 2020-10-06 22:20
@anarchylimes So, the plugin parses your manifest to find your content script.

```javascript
// rollup.config.js

import resolve from '@rollup/plugin-node-resolve'
import commonjs from '@rollup/plugin-commonjs'

import {
  chromeExtension,
  simpleReloader,
} from 'rollup-plugin-chrome-extension'

export default {
  // Point this to your manifest
  input: 'src/manifest.json',
  output: {
    dir: 'dist',
    format: 'esm',
  },
  plugins: [
    // always put chromeExtension() before other plugins
    chromeExtension(),
    simpleReloader(),
    // the plugins below are optional
    resolve(),
    commonjs(),
  ],
}
```

```jsonc
// manifest.json
{
  ...
  "content_scripts": [
    {
      "matches": [
        "http://*/*",
        "https://*/*"
      ],
      // This path is relative to the manifest.json
      "js": ["libs/content.js"]
    }
  ],
  ...
}
```

**Comment by anarchylimes** [comment] 2020-10-12 21:11
No I understand how it connects various files to the manifest. What I'm talking about is that the content script is not being injected into the page. see this simple setup.

```
{
  "manifest_version": 2,
  "name": "NAME",
  "version": "0.0.1",
  "description": "NAME DESCRIPTION",
  "permissions": ["activeTab", "tabs", "<all_urls>"],
  "content_scripts": [
    {
      "matches": ["<all_urls>"],
      "js": [
        "js/content/content.js"
      ]
    }
  ],
  "background": {
    "scripts": [
      "js/background/background.js"
    ]
  },
  "browser_action": {
    "default_icon": "img/logo.png",
    "default_title": "NAME",
    "default_popup": "html/popup.html"
  }
}
```

then inside of js/content/content.js

```
document.body.style.border = '5px solid red'
```

yet literally nothing is happening on the page when there should be a simple border around everything.

in the dist/ folder the manifest looks like this

```
{
  "manifest_version": 2,
  "name": "NAME",
  "version": "0.0.1",
  "description": "DEVELOPMENT build with simple auto-reloader\n[2020-10-12 17:05:52] waiting for changes...",
  "permissions": [
    "activeTab",
    "tabs",
    "<all_urls>"
  ],
  "content_scripts": [
    {
      "js": [
        "assets/content-script-reloader-90067bfc.js",
        "assets/content-b1554941.js"
      ],
      "matches": [
        "<all_urls>"
      ]
    }
  ],
  "background": {
    "scripts": [
      "assets/background-page-reloader-0ad65c2b.js",
      "assets/background-21b4d0ae.js"
    ],
    "persistent": true
  },
  "browser_action": {
    "default_icon": "img/logo.png",
    "default_title": "NAME",
    "default_popup": "html/popup.html"
  },
  "web_accessible_resources": [
    "js/content/content.js"
  ]
}
```

and the assets/content-b1154941.js looks like this

```
(function () {
	'use strict';

	const importPath = /*@__PURE__*/JSON.parse('"../js/content/content.js"');

	import(importPath);

}());

```

and finally that content.js has 

```
document.body.style.border = '5px solid red';
```

so why is it that the content script isn't being injected when all the paths look correct?

**Comment by jacksteamdev** [comment] 2020-10-19 22:00
@anarchylimes I copy pasted your code over and it works for me... 🤔

Make sure to reload the page the first time after you load the extension. Chrome only injects a content script when the page is loading.

I'm going to close this issue, but if you want to link to a repo that reproduces this issue, I'd be happy to look at it. [This boilerplate might be a good place to start.](https://github.com/extend-chrome/javascript-boilerplate)

**Closed by jacksteamdev** 2020-10-19 22:00 UTC

**Comment by anarchylimes** [comment] 2020-10-21 16:34
I actually figured this out and it was because I was assuming it was cross browser compatible but firefox doesn't recognize how you're loading the content / background scripts. Even with the standard boilerplate it doesn't work. Maybe that's a stretch goal!
